<?php
$sql='SELECT 	description,
				activity,
				maintenance_date,
				user,
				email
		FROM maintenance_plan
		INNER JOIN fixedassets
		ON maintenance_plan.assetid=fixedassets.assetid
		INNER JOIN www_users
		ON maintenance_plan.user=www_users.userid
	   WHERE maintenance_date >= CURDATE() AND DATEDIFF(maintenance_date,CURDATE())<=7
		';

$res = DB_query($sql);
$email=array();
while($myrow=DB_fetch_array($res)){
$email[]=$myrow['email'];

$EmailText= _('This email has been automatically generated by webERP') . "\n";
		$EmailText.= _('You are notified that there are assets which are  supposed to be maintained in less than a week  ')  . "\n";
		$EmailText.= _('Please make a requisition for those assets  ')  . "\n";
		$EmailText.= _('Asset : '.$myrow['description'].'') . "\n";
		$EmailText.= _('Activity : '. $myrow['activity'] .'') . "\n";
		$EmailText.= _('Maintenance Date : '. $myrow['maintenance_date'] .'') . "\n";
		
		}
		include ('includes/htmlMimeMail.php');
		$mail = new htmlMimeMail();
		$mail->setText($EmailText);
		$mail->SetSubject(_('MAINTENANCE REMINDER '));
		if($_SESSION['SmtpSetting'] == 0){
			$mail->setFrom($_SESSION['CompanyRecord']['coyname'] . ' <' . $_SESSION['CompanyRecord']['email'] . '>');
			$result = $mail->send($email);
		}else{
			$result = SendmailBySmtp($mail,$email);
		}


?>